Initial fork to setup rebase workflow

diff --git a/git-flow-feature b/git-flow-feature
--- a/git-flow-feature
+++ b/git-flow-feature
@@ -230,11 +230,9 @@ cmd_start() {
 }
 
 cmd_finish() {
-	DEFINE_boolean fetch false "fetch from $ORIGIN before performing finish" F
-	DEFINE_boolean rebase false "rebase instead of merge" r
 	DEFINE_boolean keep false "keep branch after performing finish" k
-	DEFINE_boolean force_delete false "force delete feature branch after finish" D
-	DEFINE_boolean squash false "squash feature during merge" S
+	DEFINE_boolean nosquash false S
+	DEFINE_boolean norebase false R
 	parse_args "$@"
 	expand_nameprefix_arg_or_current
 
@@ -284,12 +282,11 @@ cmd_finish() {
 	# sanity checks
 	require_clean_working_tree
 
-	# update local repo with remote changes first, if asked
+	# update local repo with remote changes first
 	if has "$ORIGIN/$BRANCH" $(git_remote_branches); then
-		if flag fetch; then
-			git_do fetch -q "$ORIGIN" "$BRANCH"
-			git_do fetch -q "$ORIGIN" "$DEVELOP_BRANCH"
-		fi
+	
+		git_do fetch -q "$ORIGIN" "$BRANCH"
+		git_do fetch -q "$ORIGIN" "$DEVELOP_BRANCH"
 	fi
 
 	if has "$ORIGIN/$BRANCH" $(git_remote_branches); then
@@ -298,9 +295,30 @@ cmd_finish() {
 	if has "$ORIGIN/$DEVELOP_BRANCH" $(git_remote_branches); then
 		require_branches_equal "$DEVELOP_BRANCH" "$ORIGIN/$DEVELOP_BRANCH"
 	fi
+	
+	local num_commits=$(git log --oneline "$DEVELOP_BRANCH".. | wc -l)
+
+	if [ $num_commits -eq 1 ]; then
+		echo "Only one commit on this feature. Squashing unnecessary."
+	else
+		if noflag nosquash; then
+			if ! git_do reset --soft `git merge-base "$DEVELOP_BRANCH" "$BRANCH"`; then
+				echo
+				echo "Could not execute squash. Failing."
+				echo
+				exit 1
+			fi
+			if ! git_do commit; then
+				warn "Commit failed. Did you supply a commit message?"
+				warn "Please commit manually now and retry."
+				exit 1
+			fi
+		fi
+	fi
+
 
 	# if the user wants to rebase, do that first
-	if flag rebase; then
+	if noflag norebase; then
 		if ! git flow feature rebase "$NAME" "$DEVELOP_BRANCH"; then
 			warn "Finish was aborted due to conflicts during rebase."
 			warn "Please finish the rebase manually now."
@@ -312,17 +330,7 @@ cmd_finish() {
 
 	# merge into BASE
 	git_do checkout "$DEVELOP_BRANCH"
-	if [ "$(git rev-list -n2 "$DEVELOP_BRANCH..$BRANCH" | wc -l)" -eq 1 ]; then
-		git_do merge --ff "$BRANCH"
-	else
-		if noflag squash; then
-		    git_do merge --no-ff "$BRANCH"
-		else
-			git_do merge --squash "$BRANCH"
-			git_do commit
-			git_do merge "$BRANCH"
-		fi
-	fi
+	git_do merge "$BRANCH"
 
 	if [ $? -ne 0 ]; then
 		# oops.. we have a merge conflict!
@@ -348,23 +356,19 @@ helper_finish_cleanup() {
 	# sanity checks
 	require_branch "$BRANCH"
 	require_clean_working_tree
-
-	# delete branch
-	if flag fetch; then
-		git_do push "$ORIGIN" ":refs/heads/$BRANCH"
-	fi
-	
 	
 	if noflag keep; then
-		if flag force_delete; then
-			git_do branch -D "$BRANCH"
-		else
-			git_do branch -d "$BRANCH"
+		git_do branch -d "$BRANCH"
+
+		if git_branch_exists "$ORIGIN/$BRANCH"; then
+			git_do push "$ORIGIN" ":refs/heads/$BRANCH"
 		fi
 	fi
 
 	echo
 	echo "Summary of actions:"
+	echo "- The feature branch '$BRANCH' has been squashed to one commit"
+	echo "- The feature branch '$BRANCH' has been rebased onto '$DEVELOP_BRANCH'"
 	echo "- The feature branch '$BRANCH' was merged into '$DEVELOP_BRANCH'"
 	#echo "- Merge conflicts were resolved"		# TODO: Add this line when it's supported
 	if flag keep; then
